title: Sze Hang Wong (Timothy Wong) # your name (or website title) here
logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  A dedicated and challenge loving data analyst with 10+ years of commercial experience and a master's degree in Data Science from the University of Bristol. Skillful in ETL and data analytics, I helped my team to build up our own data warehouse and automate KPI reporting, so we could focus on other ad-hoc research projects.
  <br><br>
  Currently I am keen to develop experience in work related to data science and data engineering.
  <br><br>
  <a href="https://www.linkedin.com/in/timothy-wong-a3215266">Visit my LinkedIn Profile</a> 
  <br><br>
  <a href="https://timwsh.github.io/pdf/CV%20(SZE%20HANG%20WONG%2C%20Timothy).pdf">View my CV</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'